plugins { id 'com.android.application' }
android {
    namespace 'com.remna.boost'
    compileSdk 34
    defaultConfig { applicationId 'com.remna.boost'; minSdk 26; targetSdk 34; versionCode 2; versionName '1.1' }
    signingConfigs { release { storeFile file('boost.jks'); storePassword 'boost123'; keyAlias 'boost'; keyPassword 'boost123' } }
    buildTypes { release { minifyEnabled false; signingConfig signingConfigs.release } }
    lint { checkReleaseBuilds false; abortOnError false }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
dependencies {
    implementation 'dev.rikka.shizuku:api:13.1.5'
    implementation 'dev.rikka.shizuku:provider:13.1.5'
}
